version: '2'
services:
  project_web:
    container_name: project_web
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "5000:5000"
    env_file: ./docker/app/.env_local
    depends_on:
      - project_db
    volumes:
      - .:/code
  project_db:
    container_name: project_db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./docker/db/.env_local
