"""03_addcascade

Revision ID: 1ab163c7ac66
Revises: d9cbf5452560
Create Date: 2020-10-08 03:02:51.022191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab163c7ac66'
down_revision = 'd9cbf5452560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Component_Ingredient_ingredient_id_fkey', 'Component_Ingredient', type_='foreignkey')
    op.drop_constraint('Component_Ingredient_component_id_fkey', 'Component_Ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'Component_Ingredient', 'ingredient', ['ingredient_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'Component_Ingredient', 'component', ['component_id'], ['id'], ondelete='cascade')
    op.drop_constraint('Recipe_Component_recipe_id_fkey', 'Recipe_Component', type_='foreignkey')
    op.drop_constraint('Recipe_Component_component_id_fkey', 'Recipe_Component', type_='foreignkey')
    op.create_foreign_key(None, 'Recipe_Component', 'component', ['component_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'Recipe_Component', 'recipe', ['recipe_id'], ['id'], ondelete='cascade')
    op.drop_constraint('ingredient_name_id_fkey', 'ingredient', type_='foreignkey')
    op.drop_constraint('ingredient_unit_id_fkey', 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'ingredientunit', ['unit_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'ingredient', 'ingredientname', ['name_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key('ingredient_unit_id_fkey', 'ingredient', 'ingredientunit', ['unit_id'], ['id'])
    op.create_foreign_key('ingredient_name_id_fkey', 'ingredient', 'ingredientname', ['name_id'], ['id'])
    op.drop_constraint(None, 'Recipe_Component', type_='foreignkey')
    op.drop_constraint(None, 'Recipe_Component', type_='foreignkey')
    op.create_foreign_key('Recipe_Component_component_id_fkey', 'Recipe_Component', 'component', ['component_id'], ['id'])
    op.create_foreign_key('Recipe_Component_recipe_id_fkey', 'Recipe_Component', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'Component_Ingredient', type_='foreignkey')
    op.drop_constraint(None, 'Component_Ingredient', type_='foreignkey')
    op.create_foreign_key('Component_Ingredient_component_id_fkey', 'Component_Ingredient', 'component', ['component_id'], ['id'])
    op.create_foreign_key('Component_Ingredient_ingredient_id_fkey', 'Component_Ingredient', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###
