"""01_add_component_tables

Revision ID: cab352be9c1e
Revises: 
Create Date: 2020-08-05 01:06:11.382934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab352be9c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('instuction_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ingredient_amount', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('isRequire', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredientname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredientunit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name_id'], ['ingredientname.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['ingredientunit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Component_Ingredient',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Component_Ingredient')
    op.drop_table('ingredient')
    op.drop_table('ingredientunit')
    op.drop_table('ingredientname')
    op.drop_table('component')
    # ### end Alembic commands ###
